$('.testmonals-slide').owlCarousel({
    autoplay:true,
	center:true,
	items:1,
    loop:true,
    margin:10,
    responsive:{
        0:{
            items:1
        },
		600:{
            items:1
        },
		1000:{
            items:3
        }
    }
})